Update env_hooker

diff --git a/env_hooker b/env_hooker
--- a/env_hooker
+++ b/env_hooker
@@ -1,8 +1,19 @@
 # shellcheck shell=bash
 # vi: set ft=sh:
 
+ENV_HOOKER_HOOKS=()
+
 function __env_hooker_command_exists() {
   type -t "$1" >/dev/null
+}
+
+function __env_hooker_usage() {
+  cat >&2 <<EOS
+Usage: register_env_hook <hook_file_name> <hook_function_root>
+
+  <hook_file_name>     - the file whose presence will trigger the hook
+  <hook_function_root> - the suffix for the hook functions
+EOS
 }
 
 function __env_hooker_add_env_handler() {
@@ -20,21 +31,17 @@ function __env_hooker_run_env_hook {
   local -r hook_function_root=$2
   local -r enter_hook=enter_${hook_function_root}
   local -r exit_hook=exit_${hook_function_root}
+  local -r marker=ENV_HOOK_ENTERED_${hook_function_root}
+  local entered=""
 
-  if [[ ! -n "$hook_file" || ! -n "$hook_function_root" ]]; then
-    echo "You must specify both the hook file and the function root!" >&2
-    return
-  fi
-
-  if ! __env_hooker_command_exists "${enter_hook}" || ! __env_hooker_command_exists "${exit_hook}"; then
-    echo "You must define both the ${enter_hook} and ${exit_hook} functions" >&2
-    return
-  fi
+  eval "entered=\$$marker"
 
   local current_dir="$PWD"
 
   until [[ -z "${current_dir}" ]]; do
     if [[ -f "${current_dir}/${hook_file}" ]]; then
+      [[ -n "$entered" ]] && return
+      eval "${marker}=${current_dir}"
       ${enter_hook} "${current_dir}"
       return
     fi
@@ -42,47 +49,45 @@ function __env_hooker_run_env_hook {
     current_dir="${current_dir%/*}"
   done
 
-  ${exit_hook}
+  if [[ -n "$entered" ]]; then
+    eval "unset $marker"
+    ${exit_hook}
+  fi
+}
+
+function __env_hooker_run_env_hooks {
+  for hook in "${ENV_HOOKER_HOOKS[@]}"; do
+    eval "__env_hooker_run_env_hook ${hook}"
+  done
 }
 
 function register_env_hook {
   local -r hook_file=$1
   local -r hook_function_root=$2
+  local -r enter_hook=enter_${hook_function_root}
+  local -r exit_hook=exit_${hook_function_root}
 
   if [[ ! -n "$hook_file" || ! -n "$hook_function_root" ]]; then
-    echo "You must specify both the hook file and the function root!" >&2
+    __env_hooker_usage
     return
   fi
 
-  __env_hooker_add_env_handler "__env_hooker_run_env_hook ${hook_file} ${hook_function_root}"
-}
-
-function load_env_hooks() {
-  local -r hooks_dir=${1:-~/.env_hooks}
-
-  __ENV_HOOKER_HANDLERS=""
-
-  if [[ ! -d "$hooks_dir" ]]; then
-    echo "Could not find env hooks directory: ${hooks_dir}"
+  if ! __env_hooker_command_exists "${enter_hook}" || ! __env_hooker_command_exists "${exit_hook}"; then
+    echo "Error: functions ${enter_hook}() and ${exit_hook}() must be defined before" >&2
+    echo "registering this hook" >&2
+    echo ""
+    __env_hooker_usage
     return
   fi
 
-  for hook in ${hooks_dir}/*; do
-    [[ -e $hook ]] || break
-    # shellcheck source=/dev/null
-    source "${hook}"
-  done
-
-  if [[ -n "$ZSH_VERSION" ]]; then
-    if [[ -n "$__ENV_HOOKER_HANDLERS" ]]; then
-      preexec_functions+=("$__ENV_HOOKER_HANDLERS")
-    fi
-  elif [[ -n "$BASH_VERSION" ]]; then
-    if [[ -n "$__ENV_HOOKER_HANDLERS" ]]; then
-      # shellcheck disable=SC2016
-      prompt_test='[[ "$BASH_COMMAND" != "$PROMPT_COMMAND" ]]'
-      # shellcheck disable=SC2064
-      trap "$prompt_test && $__ENV_HOOKER_HANDLERS" DEBUG
-    fi
-  fi
+  ENV_HOOKER_HOOKS+=("${hook_file} ${hook_function_root}")
 }
+
+if [[ -n "$ZSH_VERSION" ]]; then
+  preexec_functions+=("__env_hooker_run_env_hooks")
+elif [[ -n "$BASH_VERSION" ]]; then
+  # shellcheck disable=SC2016
+  prompt_test='[[ "$BASH_COMMAND" != "$PROMPT_COMMAND" ]]'
+  # shellcheck disable=SC2064
+  trap "$prompt_test && __env_hooker_run_env_hooks" DEBUG
+fi
